"""Initial migrations

Revision ID: 976d789998e6
Revises:
Create Date: 2025-05-11 11:11:07.755065

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "976d789998e6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_player_id"), "player", ["id"], unique=False)
    op.create_table(
        "tournament",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("max_players", sa.Integer(), nullable=False),
        sa.Column("start_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("max_players > 1", name="check_max_players_positive"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tournament_id"), "tournament", ["id"], unique=False)
    op.create_index(op.f("ix_tournament_name"), "tournament", ["name"], unique=False)
    op.create_table(
        "registration_card",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tournament_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column(
            "registered_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["player_id"], ["player.id"], onupdate="CASCADE"),
        sa.ForeignKeyConstraint(
            ["tournament_id"], ["tournament.id"], onupdate="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("registration_card")
    op.drop_index(op.f("ix_tournament_name"), table_name="tournament")
    op.drop_index(op.f("ix_tournament_id"), table_name="tournament")
    op.drop_table("tournament")
    op.drop_index(op.f("ix_player_id"), table_name="player")
    op.drop_table("player")
    # ### end Alembic commands ###
